# This is a basic workflow to help you get started with Actions

name: Readme Update

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 */1 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Check for Changes
        id: check_changes
        run: |
          git diff --exit-code || echo "Files have changed"
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Update README
        run: npm start
      - name: Commit README
        if: steps.check_changes.outputs.return-code == '0'
        run: |
          git add .
          git config --local user.email "91957568+h1s0s@users.noreply.github.com"
          git config --local user.name "HANSANGSEON"
          git commit -m "Auto commit - Changes detected"
          git push