# This is a basic workflow to help you get started with Actions

name: Readme Update

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 0 */3 * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Update README
        run: npm start
      - name: Stage changes
        run: git add .
      - name: Check for changes
        id: check
        run: |
          git diff --staged --quiet || echo "::set-output name=changed::true"
      - name: Commit README
        run: |
            git config --local user.email "91957568+h1s0s@users.noreply.github.com"
            git config --local user.name "h1s0s"
            git commit -m "Update README.md"
            git push
        if: steps.check.outputs.changed == 'true'